# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mishal Awadah
tagline:          'An online portfolio'
description:      'Software engineer, thinker, dreamer.'
url:              "awadah.me"
baseurl:          /

author:
  name:           'Mish Awadah'
  url:            https://twitter.com/bish3al

twitter_username: bish3al
github_username:  emish

# paginate:         5
# gems: [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/emish
